# --------------------------------------------------------------------------
# Real .Rdata files from released versions, read by the current one
#
# The guiding constraint made mechanical from the other direction: researchers
# re-run stored scripts years later, against stimulus sets generated by whatever
# rcicr they had then. Every other test builds its fixture with the *current*
# generator, so none of them can catch a field this version expects and an older
# one never wrote.
#
# The fixtures are what those releases actually wrote -- generated by installing
# each tag and letting it run, see tools/make-legacy-rdata.R -- for the reason
# the release gate runs the old code rather than trusting the golden master. What
# they contain is not a reconstruction:
#
#   1.0.1  no `nscales`, no `sigma` (both added in 1.1.0). generator_version
#          '0.4.0', p$generator_version '1.0.1'.
#   1.1.0  has nscales and sigma. generator_version still '0.4.0',
#          p$generator_version '1.1.0'.
#
# That both files really do claim 0.4.0 while `p` holds the truth is the measured
# basis for preferring p$generator_version -- see DECISIONS.md, "`generator_version`
# in old `.Rdata` files is not trustworthy".
#
# Do not regenerate these to make a red test pass. A failure here means this
# version can no longer read a file a researcher already has.
# --------------------------------------------------------------------------

legacy_versions <- c("1.0.1", "1.1.0")

legacy_fixture <- function(version) {
  path <- test_path("fixtures", paste0("legacy-rdata-", version, ".Rdata"))
  skip_if_not(file.exists(path), paste("no legacy fixture for", version))
  path
}

# generateCI() writes to disk, so each call gets its own directory. The fixture
# itself is never written to: it is copied first, because a test that mutated it
# would silently rewrite a committed artefact.
local_fixture_copy <- function(version, env = parent.frame()) {
  dir <- withr::local_tempdir(.local_envir = env)
  dest <- file.path(dir, basename(legacy_fixture(version)))
  file.copy(legacy_fixture(version), dest)
  dest
}

test_that("the current generateCI() reads .Rdata files written by older releases", {
  skip_if_not_installed("withr")

  for (version in legacy_versions) {
    rdata <- local_fixture_copy(version)

    ci <- generateCI(
      stimuli = 1:6, responses = rep(c(1, -1), 3), baseimage = "base",
      rdata = rdata, save_as_png = FALSE
    )

    # A classification image at the fixture's own size, and real numbers in it:
    # "it ran" is not the claim, "it produced a CI" is.
    expect_true(is.matrix(ci$ci), info = version)
    expect_equal(dim(ci$ci), c(32L, 32L), info = version)
    expect_false(anyNA(ci$ci), info = version)
    expect_gt(stats::sd(as.vector(ci$ci)), 0)
  }
})

test_that("a 1.0.1 file, which predates nscales and sigma, still yields a CI", {
  skip_if_not_installed("withr")

  # The specific hazard: 1.0.1 never wrote these two fields, so anything reading
  # them has to cope with their absence rather than erroring or -- worse --
  # silently substituting a default that changes the noise basis.
  e <- new.env()
  load(legacy_fixture("1.0.1"), envir = e)
  expect_false(exists("nscales", envir = e, inherits = FALSE))
  expect_false(exists("sigma", envir = e, inherits = FALSE))

  ci <- generateCI(
    stimuli = 1:6, responses = rep(c(1, -1), 3), baseimage = "base",
    rdata = local_fixture_copy("1.0.1"), save_as_png = FALSE
  )
  expect_false(anyNA(ci$ci))
})

test_that("the writing version is read from p, not from the field that says 0.4.0", {
  skip_if_not_installed("withr")

  # The synthetic version of this is in test-rdata-writer-note.R; this is the
  # same assertion against files a release actually wrote.
  for (version in legacy_versions) {
    e <- new.env()
    load(legacy_fixture(version), envir = e)
    expect_equal(as.character(get("generator_version", envir = e)), "0.4.0", info = version)
    expect_equal(as.character(get("p", envir = e)$generator_version), version, info = version)

    rdata <- local_fixture_copy(version)
    mutate_rdata(rdata, .remove = "stimuli_params")

    msg <- tryCatch(
      generateCI(stimuli = 1:6, responses = rep(c(1, -1), 3), baseimage = "base",
                 rdata = rdata, save_as_png = FALSE),
      error = conditionMessage
    )

    expect_match(msg, paste("written by rcicr", version), fixed = TRUE)
    expect_false(grepl("0.4.0", msg, fixed = TRUE))
  }
})
