# --------------------------------------------------------------------------
# Real .Rdata files from released versions, read by the current one
#
# The guiding constraint made mechanical from the other direction: researchers
# re-run stored scripts years later, against stimulus sets generated by whatever
# rcicr they had then. Every other test builds its fixture with the *current*
# generator, so none of them can catch a field this version expects and an older
# one never wrote.
#
# The fixtures are what those releases actually wrote -- generated by installing
# each tag and letting it run, see tools/make-legacy-rdata.R -- for the reason
# the release gate runs the old code rather than trusting the golden master. What
# they contain is not a reconstruction:
#
#   1.0.1  no `nscales`, no `sigma` (both added in 1.1.0). generator_version
#          '0.4.0', p$generator_version '1.0.1'.
#   1.1.0  has nscales and sigma. generator_version still '0.4.0',
#          p$generator_version '1.1.0'.
#
# That both files really do claim 0.4.0 while `p` holds the truth is the measured
# basis for preferring p$generator_version -- see DECISIONS.md, "`generator_version`
# in old `.Rdata` files is not trustworthy".
#
# Do not regenerate these to make a red test pass. A failure here means this
# version can no longer read a file a researcher already has.
# --------------------------------------------------------------------------

legacy_versions <- c("1.0.1", "1.1.0")

legacy_fixture <- function(version) {
  path <- test_path("fixtures", paste0("legacy-rdata-", version, ".Rdata"))
  # Committed, mandatory assets, so a missing one fails rather than skips: a skip
  # reads as "this passed" at a glance, and the scenario it would hide -- the
  # fixture deleted, renamed, or left out of a built package -- is precisely the
  # safeguard silently disappearing while CI stays green.
  expect_true(file.exists(path), info = paste("missing legacy fixture:", path))
  path
}

# generateCI() writes to disk, so each call gets its own directory. The fixture
# itself is never written to: it is copied first, because a test that mutated it
# would silently rewrite a committed artefact.
#
# `base_face_files` is repointed at a base image written here. These files store
# an *absolute* path from the machine that generated them -- a real property of
# every `.Rdata` rcicr writes, and the reason a researcher who moved their base
# image cannot re-generate either. Only readers that re-generate stimuli
# (generateReferenceDistribution2IFC()) ever open it; generateCI() works from the
# `base_faces` matrix already in the file. The image is the same synthetic square
# the rest of the suite uses, and its content is irrelevant to what is asserted.
local_fixture_copy <- function(version, env = parent.frame()) {
  dir <- withr::local_tempdir(.local_envir = env)
  dest <- file.path(dir, basename(legacy_fixture(version)))
  file.copy(legacy_fixture(version), dest)

  base_png <- make_square_png(file.path(dir, "base.png"), size = 32, seed = 1)
  mutate_rdata(dest, base_face_files = list(base = base_png))

  dest
}

test_that("the current generateCI() reads .Rdata files written by older releases", {
  skip_if_not_installed("withr")

  for (version in legacy_versions) {
    rdata <- local_fixture_copy(version)

    ci <- generateCI(
      stimuli = 1:6, responses = rep(c(1, -1), 3), baseimage = "base",
      rdata = rdata, save_as_png = FALSE
    )

    # A classification image at the fixture's own size, and real numbers in it:
    # "it ran" is not the claim, "it produced a CI" is.
    expect_true(is.matrix(ci$ci), info = version)
    expect_equal(dim(ci$ci), c(32L, 32L), info = version)
    expect_false(anyNA(ci$ci), info = version)
    expect_gt(stats::sd(as.vector(ci$ci)), 0)
  }
})

test_that("a 1.0.1 file genuinely lacks nscales and sigma", {
  e <- new.env()
  load(legacy_fixture("1.0.1"), envir = e)

  expect_false(exists("nscales", envir = e, inherits = FALSE))
  expect_false(exists("sigma", envir = e, inherits = FALSE))
  # noise_type predates 1.0.1, so this file has it -- which is why the test below
  # expects the nscales warning and not the noise_type one.
  expect_true(exists("noise_type", envir = e, inherits = FALSE))
})

reference_norms_for <- function(rdata) {
  seen <- character()
  withCallingHandlers(
    generateReferenceDistribution2IFC(rdata, iter = 3, ncores = 1),
    warning = function(cond) {
      seen <<- c(seen, conditionMessage(cond))
      invokeRestart("muffleWarning")
    }
  )
  after <- new.env()
  load(rdata, envir = after)
  list(warnings = seen, norms = after$reference_norms)
}

test_that("the missing-nscales fallback assumes the historical default of 5", {
  skip_if_not_installed("withr")

  # generateCI() never reads nscales or sigma, so it cannot exercise the
  # compatibility fallbacks -- those are in generateReferenceDistribution2IFC(),
  # which re-generates the stimuli and therefore needs the noise-basis parameters
  # 1.0.1 did not save. This is the reader that would break if they were removed.
  #
  # That re-generation rebuilds the basis from the nscales *value*, not from the
  # stored stimuli, so what this pins is the value the fallback picks: it must be
  # 5, the default a 1.0.1 user actually generated with, or the null is built on a
  # different basis than the participant saw -- which finishes just as happily and
  # is wrong. So "finite norms" is not the claim; equalling an explicit 5, and
  # differing from any other value, is. The fixture is likewise generated at 5
  # (tools/make-legacy-rdata.R) so it represents that real default case.
  fallback <- reference_norms_for(local_fixture_copy("1.0.1"))

  explicit_5 <- local_fixture_copy("1.0.1")
  mutate_rdata(explicit_5, nscales = 5)
  explicit_5 <- reference_norms_for(explicit_5)

  explicit_3 <- local_fixture_copy("1.0.1")
  mutate_rdata(explicit_3, nscales = 3)
  explicit_3 <- reference_norms_for(explicit_3)

  expect_true(any(grepl("does not contain `nscales`", fallback$warnings, fixed = TRUE)))
  expect_false(any(grepl("does not contain `noise_type`", fallback$warnings, fixed = TRUE)))
  expect_false(any(grepl("does not contain `nscales`", explicit_5$warnings, fixed = TRUE)))

  # The fallback picks 5 specifically: identical to an explicit 5, and the value
  # is load-bearing, so a different one gives a different null.
  expect_identical(fallback$norms, explicit_5$norms)
  expect_false(identical(fallback$norms, explicit_3$norms))
  expect_length(fallback$norms, 3)
  expect_false(anyNA(fallback$norms))
})

test_that("a 1.1.0 file's saved nscales is honoured, not the fallback", {
  skip_if_not_installed("withr")

  # 1.1.0 records nscales, and this fixture records 1 -- deliberately unlike the
  # fallback's 5. "No fallback warning" alone would not catch the reader ignoring
  # the saved value and using 5 anyway: no field is missing, so no warning fires,
  # and the null is still finite. So the check is that the null matches an
  # explicit 1 and differs from an explicit 5 -- the value that a saved-nscales
  # regression would substitute.
  e <- new.env()
  load(legacy_fixture("1.1.0"), envir = e)
  expect_equal(get("nscales", envir = e), 1)

  saved <- reference_norms_for(local_fixture_copy("1.1.0"))

  as_1 <- local_fixture_copy("1.1.0")
  mutate_rdata(as_1, nscales = 1)
  as_1 <- reference_norms_for(as_1)

  as_5 <- local_fixture_copy("1.1.0")
  mutate_rdata(as_5, nscales = 5)
  as_5 <- reference_norms_for(as_5)

  expect_false(any(grepl("does not contain `nscales`", saved$warnings, fixed = TRUE)))
  expect_identical(saved$norms, as_1$norms)
  expect_false(identical(saved$norms, as_5$norms))
})

test_that("the writing version is read from p, not from the field that says 0.4.0", {
  skip_if_not_installed("withr")

  # The synthetic version of this is in test-rdata-writer-note.R; this is the
  # same assertion against files a release actually wrote.
  for (version in legacy_versions) {
    e <- new.env()
    load(legacy_fixture(version), envir = e)
    expect_equal(as.character(get("generator_version", envir = e)), "0.4.0", info = version)
    expect_equal(as.character(get("p", envir = e)$generator_version), version, info = version)

    rdata <- local_fixture_copy(version)
    mutate_rdata(rdata, .remove = "stimuli_params")

    msg <- tryCatch(
      generateCI(stimuli = 1:6, responses = rep(c(1, -1), 3), baseimage = "base",
                 rdata = rdata, save_as_png = FALSE),
      error = conditionMessage
    )

    expect_match(msg, paste("written by rcicr", version), fixed = TRUE)
    expect_false(grepl("0.4.0", msg, fixed = TRUE))
  }
})
