# ----------
# rcicr demo
# ----------
#
# Ron Dotsch (rdotsch@gmail.com)
#
# These data are collected by Judt Fan (jefan@princeton.edu) using a task based on Dotsch & Todorov (2012). 
# These scripts and data files can be downloaded from http://ron.dotsch.org/rcicr/. This script works from 
# rcicr version 0.2.5 and up.
#
# The script below shows how to analyze your data after stimuli have been generated and data has been collected
# using a 2IFC reverse correlation task. In 100 trials, seven participants judged which of two images looked
# the most as if it had some trait (trustworthy, untrustworthy, dominant, submissive).
# 
# The responses are collected in rcicrdemo.csv. The information about the presented stimuli that is used in the
# analysis is contained in rcicrdemo.Rdata. This file is automatically generated by rcicr when the stimuli are
# generated and contains a full archive of all stimulus parameters, including base image.
#
# For more information, please visit http://ron.dotsch.org/rcicr/. Subscribe to the user mailing list to stay
# up to date at http://lists.r-forge.r-project.org/pipermail/rcicr-users/. You can use this list to ask questions.
#
# ----------


# Load reverse correlation package ("rcicr")
library(rcicr)

# Base image name used during stimulus generation
baseimage <- 'base'

# File containing the contrast parameters (this file was created during stimulus generation)
rdata <- 'rcicrdemo.Rdata'

# Load response data
responsedata <- read.csv('rcicrdemo.csv')

# Batch generate classification images by subject
cis <- batchGenerateCI2IFC(responsedata, 'subject', 'stimulus', 'response', baseimage, rdata)

# Batch generate classification images by trait
cis <- batchGenerateCI2IFC(responsedata, 'trait', 'stimulus', 'response', baseimage, rdata)


