#!/usr/bin/env Rscript

# CITATION.cff is generated by cffr from DESCRIPTION and inst/CITATION. This
# regenerates it and compares, so no field can drift from its source, and
# validates the committed file against the CFF schema, because GitHub declines to
# render the "Cite this repository" button on a file it cannot parse and says
# nothing. Regenerate with:
#
#   cffr::cff_write("DESCRIPTION", dependencies = FALSE, gh_keywords = FALSE)
#
# `dependencies = FALSE` leaves out the 350 lines describing every dependency's
# authors, whose years are read from whichever versions happen to be installed.
# `gh_keywords = FALSE` keeps generation off the network.

want <- cffr::cff_create("DESCRIPTION", dependencies = FALSE, gh_keywords = FALSE)
have <- cffr::cff_read("CITATION.cff")

# inst/CITATION derives its year from the clock when DESCRIPTION carries no
# publication date, so this one field changes on 1 January with nothing else. A
# comparison including it would redden a required check on a calendar boundary.
drop_year <- function(x) {
  x$`preferred-citation`$year <- NULL
  x
}

differing <- Filter(
  function(key) !identical(drop_year(want)[[key]], drop_year(have)[[key]]),
  union(names(want), names(have))
)

for (key in setdiff(union(names(want), names(have)), differing)) {
  cat("  ok   ", key, "\n", sep = "")
}
for (key in differing) {
  cat("  FAIL ", key, "\n    generated: ", yaml::as.yaml(want[[key]]),
    "    committed: ", yaml::as.yaml(have[[key]]),
    sep = ""
  )
}

if (length(differing)) {
  cat("\nCITATION.cff does not match what cffr generates from DESCRIPTION and",
    " inst/CITATION.\nRegenerate it (see the top of this script), or fix the source",
    " it should have matched.\n",
    sep = ""
  )
  quit(status = 1L)
}

cat("\nCITATION.cff matches its sources. Validating against the CFF schema:\n")
if (!isTRUE(cffr::cff_validate("CITATION.cff", verbose = TRUE))) quit(status = 1L)
